server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/takehome}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
